/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>
#include "defines.h"
#include "delay.h"

uint32_t lastmsg;
int main(void)
{
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODER(MODE_OUT, LED);
	GPIOX_OTYPER(MODE_OT_PP, LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH, LED);
	GPIOX_PUPDR(MODE_PU_NONE, LED);

	delay_init_it();
	lastmsg = millis();
    /* Loop forever */
	for(;;){
//		GPIOX_ODR(LED) ^= 1;
//		delay_ms(100);
		if((millis() - lastmsg) > 10){

			GPIOX_ODR(LED) ^= 1;
			lastmsg = millis();
		}
		//todo

	}
}
