/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes--------------------------------------------------------------------*/
#include <stdint.h>
#include <stm32f4xx.h>

/*Function prototype----------------------------------------------------------*/
/**
 * @brief funcion que selecciona el HSI como fuente para el SYSCLK
 */
void HSI_Sysclk(void);
/**
 * @brief funcion que selecciona el HSE como fuente para el SYSCLK
 */
void HSE_Sysclk(void);

int main(void)
{
	HSI_Sysclk();
	HSE_Sysclk();
    /* Loop forever */
	for(;;);
}
/*Function definition ----------------------------------------------------------*/
/**
 * @brief funcion que selecciona el HSI como fuente para el SYSCLK
 */
void HSI_Sysclk(void){
	/*habilitar el HSI*/
	RCC->CR |= RCC_CR_HSION;
	/*Esperar que este listo*/
	while(!(RCC->CR & RCC_CR_HSIRDY));
	/*Seleccionar el HSI como fuente de reloj del SYSCLK*/
	RCC->CFGR &=~ (RCC_CFGR_SW);
	while(RCC->CFGR & RCC_CFGR_SWS);

	SystemCoreClockUpdate();
}
/**
 * @brief funcion que selecciona el HSE como fuente para el SYSCLK
 */
void HSE_Sysclk(void){
	/*habilitar el HSE*/
	RCC->CR |= RCC_CR_HSEON | RCC_CR_HSEBYP;
	while(!(RCC->CR & RCC_CR_HSERDY));
	/*Se selecciona el HSE COMO FUENTE DE RELOJ DEL SISTEMA*/
	RCC->CFGR = RCC_CFGR_SW_HSE;				//Se selecciona el HSE Como fuente sysclk
	while(!(RCC->CFGR & RCC_CFGR_SWS_HSE));		//se espera que se haga el cambio
	SystemCoreClockUpdate();
}
