/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>
#include <defines.h>

#define __weak __attribute__((weak))
/**
 * @brief
 */
void EXTI13_Init(void);


void EXIT_IRQHandling(uint32_t pin_number);

void EXTI_ApplicationCallback(uint32_t pinnumber);

int main(void)
{
	RCC->AHB1ENR |= GPIOX_CLOCK(BUTTON) | GPIOX_CLOCK(LED);
	//PC13
	GPIOX_MODER(MODE_DIGITAL_INPUT, BUTTON);
	//PA5
	GPIOX_MODER(MODE_OUT, LED);
	EXTI13_Init();
    /* Loop forever */
	for(;;){

	}
}

void EXTI13_Init(void){

	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	//CONFIGURACION LOCAL
	/*1. habilitar el bit de enmascaramiento*/
	EXTI->IMR |= EXTI_IMR_IM13;
	/*2. seleccionar el borde de disparo de la IT*/
	EXTI->FTSR |= EXTI_FTSR_TR13;					//IT para exti13 flanco decendente
	/*3. asignar el pin a al linea EXTI1*/
	SYSCFG->EXTICR[3] &=~ SYSCFG_EXTICR4_EXTI13;	//clear
	SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;	//PC13
	//CONFIGURACION GLOBAL O CONFIGURACION EN LA NVIC
	//PRIORIDAD
	NVIC_SetPriority(EXTI15_10_IRQn, 3);
	//HABILITAR LA IT
	NVIC_EnableIRQ(EXTI15_10_IRQn);

	return;
}

void EXIT_IRQHandling(uint32_t pin_number){
	//CLEAR
	EXTI->PR |= 1U<<pin_number;
	EXTI_ApplicationCallback(pin_number);
}

__weak void EXTI_ApplicationCallback(uint32_t pinnumber){
	if(pinnumber == 13){
		//todo
		GPIOX_ODR(LED) ^= 1;
	}else if(pinnumber == 15){
		//todo

	}
	//....
}


