/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>
#include "Config.h"
#include "delay.h"
#include "LCD.h"


/**
 * Configuracion de la flash
 */
void flash_cofig(void);
/**
 * Selecciona el HSE como sysclk
 */
void HSE_Config(void);
/**
 * Configurar el PLL  a 84MZh
 */
void PLL_Config(void);

uint32_t systemFreq;


uint8_t customChar[] = {
        0x1F,    // xxx 11111
        0x11,    // xxx 10001
        0x11,    // xxx 10001
        0x11,    // xxx 10001
        0x11,    // xxx 10001
        0x11,    // xxx 10001
        0x11,    // xxx 10001
        0x1F    // xxx 11111
    };
int main(void)
{
	uint32_t count;
	flash_cofig();
	//PLL_Config();
/**********************************************/
	delay_init();
/**********************************************/
	LCD_Init(20, 4);
	LCD_CreateChar(0, customChar);
	LCD_PutCustom(10, 0, 0);
	delay_ms(2000);
	LCD_Clear();
	LCD_Puts(0, 0, "hola mundo\n\r JEFFRY Q. B");
	LCD_BlinkOn();
	LCD_Puts(0, 2, "STM32F401RE");
	LCD_Printf(0, 0, "esto es prueba->%u",10);
	delay_ms(1000);

    /* Loop forever */
	for(;;){
		LCD_Clear();
		LCD_Printf(0, 0, "CONTEO->%u",count);
		count++;
		delay_ms(500);
	}
}

void flash_cofig(void){
	FLASH->ACR |= 1<<9;							//1: Instruction cache is enabled
	FLASH->ACR |= 1<<10;						//1: Data cache is enabled
	FLASH->ACR |= 1<<8;							//1: Prefetch is enabled
	//SE HABILITAN ALGUNOS CLOCK
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	RCC->APB1ENR |= RCC_APB1ENR_PWREN;
}

void HSE_Config(void){
	RCC->CR |= RCC_CR_HSEON | RCC_CR_HSEBYP;	//se habilita el HSE en modo BYPASS
	while(!(RCC->CR & RCC_CR_HSERDY));			//se espera que el HSE este listo
	RCC->CFGR = RCC_CFGR_SW_HSE;				//Se selecciona el HSE Como fuente sysclk
	while(!(RCC->CFGR & RCC_CFGR_SWS_HSE));		//se espera que se haga el cambio
	SystemCoreClockUpdate();
}


/**
 * @brief PLL config
 * configura el PLL  a 84MHz
 */
void PLL_Config(void){
	HSE_Config();
	RCC->CR &=~ (1U<<24);
	while(RCC->CR & 1U<<25);
	/*configure PL before enabling it*/
	//1. PLL clock source
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;	//select HSE CLOCK SOURCE
	//2. cofigure division factor (M, N, P , Q)
	/**
	 * 	f(VCO clock) = f(PLL clock input) Ã— (PLLN / PLLM)	(192 and 432 MHz)
	 * 	f(PLL general clock output) = f(VCO clock) / PLLP  	<= 84MHz
	 */
	//M
	RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLM;
	RCC->PLLCFGR |= 4U;							//VCO input frequency (1MHz to 2MHz)
	//N
	RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLN;
	RCC->PLLCFGR |= 168U<<6;					//168MHZ
	//P
	RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLP;
	RCC->PLLCFGR |= 1U<<16;						//84MHz
	//3. enable PLL
	RCC->CR |= RCC_CR_PLLON;
	while(!(RCC->CR & RCC_CR_PLLRDY));			//Waint until
	/*configure AHBx, APBx precaler*/
	RCC->CFGR = 0x00000000;						//reset
	RCC->CFGR |= 0b100<<10;						//100: AHB clock divided by 2
	/*configure flash latency*/
	FLASH->ACR &=~ FLASH_ACR_LATENCY;
	FLASH->ACR |= FLASH_ACR_LATENCY_2WS;
	/*select system clock source*/
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while(!(RCC->CFGR & RCC_CFGR_SWS_PLL));		//wait PLL ready as system clock
	SystemCoreClockUpdate();
	return;
}

int __io_putchar(int ch){
	uint8_t c = ch & 0xFF;
	ITM_SendChar(c);
	return ch;
}
